name: rss
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  cloud_firestore_odm: ^1.0.0-dev.83
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.5
  cloud_firestore_odm_generator: ^1.0.0-dev.85
  # flutter_lints: ^2.0.0
  json_serializable: ^6.8.0
  stacked_generator: ^1.3.3


flutter:
  uses-material-design: true

