// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfcDxOTsHnzUb6Jey2KFkYUGJTQ1IDmyE',
    appId: '1:197707162705:web:023d7aed41db4650d94470',
    messagingSenderId: '197707162705',
    projectId: 'rss-spaced-rep',
    authDomain: 'rss-spaced-rep.firebaseapp.com',
    storageBucket: 'rss-spaced-rep.appspot.com',
    measurementId: 'G-HD9VFWLY7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGcmfrYSJEVG0JJZlqTCs-WcjhjrCPACQ',
    appId: '1:197707162705:android:c3713a2d4371b14ad94470',
    messagingSenderId: '197707162705',
    projectId: 'rss-spaced-rep',
    storageBucket: 'rss-spaced-rep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJi332UtF9oMfG_KmzxB9QFViJc0DBghU',
    appId: '1:197707162705:ios:00fe231fc51dba65d94470',
    messagingSenderId: '197707162705',
    projectId: 'rss-spaced-rep',
    storageBucket: 'rss-spaced-rep.appspot.com',
    iosBundleId: 'com.example.rss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJi332UtF9oMfG_KmzxB9QFViJc0DBghU',
    appId: '1:197707162705:ios:00fe231fc51dba65d94470',
    messagingSenderId: '197707162705',
    projectId: 'rss-spaced-rep',
    storageBucket: 'rss-spaced-rep.appspot.com',
    iosBundleId: 'com.example.rss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfcDxOTsHnzUb6Jey2KFkYUGJTQ1IDmyE',
    appId: '1:197707162705:web:c972b2b805a69f53d94470',
    messagingSenderId: '197707162705',
    projectId: 'rss-spaced-rep',
    authDomain: 'rss-spaced-rep.firebaseapp.com',
    storageBucket: 'rss-spaced-rep.appspot.com',
    measurementId: 'G-YKGW3PPB03',
  );
}
